### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by acenkus** [vexus2/CakeStorm#37]
In Storm I get IDE Fatal Error.
![image](https://cloud.githubusercontent.com/assets/5094605/25178270/d3e3f244-250d-11e7-9822-7c75fff7cc7b.png)

`Path passed to JarFileSystem must have jar separator '!/': C:/Users/User/AppData/Local/JetBrains/Toolbox/app/View/toplevel/Couchbase\\ViewQuery.ctp`

Details table:

`ath passed to JarFileSystem must have jar separator '!/': C:/Users/User/AppData/Local/JetBrains/Toolbox/app/View/toplevel/Couchbase\\ViewQuery.ctp
java.lang.AssertionError: Path passed to JarFileSystem must have jar separator '!/': C:/Users/User/AppData/Local/JetBrains/Toolbox/app/View/toplevel/Couchbase\\ViewQuery.ctp
	at com.intellij.openapi.vfs.impl.jar.JarFileSystemImpl.extractRootPath(JarFileSystemImpl.java:93)
	at com.intellij.openapi.vfs.newvfs.VfsImplUtil.a(VfsImplUtil.java:153)
	at com.intellij.openapi.vfs.newvfs.VfsImplUtil.refreshAndFindFileByPath(VfsImplUtil.java:120)
	at com.intellij.openapi.vfs.impl.jar.JarFileSystemImpl.refreshAndFindFileByPath(JarFileSystemImpl.java:127)
	at com.intellij.openapi.vfs.impl.VirtualFileManagerImpl.refreshAndFindFileByUrl(VirtualFileManagerImpl.java:147)
	at com.vexus2.cakestorm.reference.StringLiteralReferenceProvider.getReferencesByElement(StringLiteralReferenceProvider.java:56)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.getReferences(ReferenceProvidersRegistryImpl.java:135)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.mapNotEmptyReferencesFromProviders(ReferenceProvidersRegistryImpl.java:123)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.doGetReferencesFromProviders(ReferenceProvidersRegistryImpl.java:102)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:66)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistry.getReferencesFromProviders(ReferenceProvidersRegistry.java:60)
	at com.jetbrains.php.lang.psi.elements.impl.StringLiteralExpressionImpl.getReferences(StringLiteralExpressionImpl.java:293)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassAliasImpl.getOriginalInternal(PhpClassAliasImpl.kt:61)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassAliasImpl.access$getOriginalInternal(PhpClassAliasImpl.kt:33)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassAliasImpl$original$1.compute(PhpClassAliasImpl.kt:45)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassAliasImpl$original$1.compute(PhpClassAliasImpl.kt:33)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassAliasImpl.getOriginal(PhpClassAliasImpl.kt:43)
	at com.jetbrains.php.lang.psi.elements.impl.PhpClassAliasImpl.getIcon(PhpClassAliasImpl.kt:243)
	at com.jetbrains.php.completion.PhpLookupElement.updatePresentation(PhpLookupElement.java:90)
	at com.jetbrains.php.completion.PhpLookupElement.<init>(PhpLookupElement.java:75)
	at com.jetbrains.php.completion.PhpVariantsUtil.getLookupItem(PhpVariantsUtil.java:174)
	at com.jetbrains.php.completion.PhpVariantsUtil.getLookupItemsForClasses(PhpVariantsUtil.java:62)
	at com.jetbrains.php.completion.PhpCompletionContributor$PhpClassRefCompletionProvider.addClassesContextAware(PhpCompletionContributor.java:643)
	at com.jetbrains.php.completion.PhpCompletionContributor$PhpClassRefCompletionProvider.addCompletions(PhpCompletionContributor.java:601)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:151)
	at com.jetbrains.php.completion.PhpCompletionContributor.fillCompletionVariants(PhpCompletionContributor.java:300)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:138)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:131)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:88)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:151)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:110)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.a(CompletionProgressIndicator.java:831)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.access$600(CompletionProgressIndicator.java:93)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator$1CalculateItems.run(CompletionProgressIndicator.java:813)
	at com.intellij.codeInsight.completion.AsyncCompletion.b(CompletionThreading.java:108)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:931)
	at com.intellij.codeInsight.completion.AsyncCompletion.a(CompletionThreading.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.codeInsight.completion.AsyncCompletion.a(CompletionThreading.java:103)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by mtancoigne** [comment]
Hi !
I have the same message under Linux: 
```
Path passed to JarFileSystem must have jar separator '!/': /home/user/.local/share/JetBrains/Toolbox/app/View/toplevel/Couchbase\\ViewQuery.ctp
```

**Comment by trevrobwhite** [comment]
I've got the same issue under phpStorm 2017.2 EAP (Windows 10 x64)
